name: Build
on:
  push:
    branches:
      - main
      - v*
    tags:
      - "*"
  pull_request:

jobs:
  single-header:
    name: Single header
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2

    - name: Prepare CMake config
      run: cmake -S . -B build -DCLI11_SINGLE_FILE=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Make package
      run: cmake --build build --target package_source 

    - name: Copy source packages
      run: |
        mkdir -p CLI11-Source
        cp build/CLI11-*-Source.* CLI11-Source
        cp build/CLI11-*-Source.* .

    - name: Make header
      run: cmake --build build --target CLI11-generate-single-file

    - name: Copy file to main folder
      run: cp build/include/CLI11.hpp CLI11.hpp

    - name: Rich Code Nav
      uses: microsoft/RichCodeNavIndexer@v0.1.16
      with:
        repo-token: ${{ github.token }}
        languages: cpp
